//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.22 at 06:54:51 PM MSK 
//


package rot.tot.ru.rotrequestresponse._1_0;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for NPAListItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NPAListItemType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="npaId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="region" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" minOccurs="0"/&gt;
 *         &lt;element name="npaType" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" minOccurs="0"/&gt;
 *         &lt;element name="npaTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="npaApprovingAuthority" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="npaAcceptanceDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="npaPublicId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="minustRegistryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="minustRegistryNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="npaLinkPravoGovRu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="oivData" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}OivDataType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NPAListItemType", propOrder = {
        "id",
    "npaId",
    "region",
    "npaType",
    "npaTitle",
    "npaApprovingAuthority",
    "npaAcceptanceDate",
    "npaPublicId",
    "minustRegistryDate",
    "minustRegistryNumber",
    "npaLinkPravoGovRu",
    "oivData"
})
@Document
public class NPAListItemType {

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Id
    protected String id;

    protected String npaId;
    protected CodeTitleType region;
    protected CodeTitleType npaType;
    protected String npaTitle;
    protected List<CodeTitleType> npaApprovingAuthority;
    @XmlSchemaType(name = "dateTime")
    protected Date npaAcceptanceDate;
    protected String npaPublicId;
    @XmlSchemaType(name = "dateTime")
    protected Date minustRegistryDate;
    protected String minustRegistryNumber;
    protected String npaLinkPravoGovRu;
    protected List<OivDataType> oivData;

    /**
     * Gets the value of the npaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpaId() {
        return npaId;
    }

    /**
     * Sets the value of the npaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpaId(String value) {
        this.npaId = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link CodeTitleType }
     *     
     */
    public CodeTitleType getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeTitleType }
     *     
     */
    public void setRegion(CodeTitleType value) {
        this.region = value;
    }

    /**
     * Gets the value of the npaType property.
     * 
     * @return
     *     possible object is
     *     {@link CodeTitleType }
     *     
     */
    public CodeTitleType getNpaType() {
        return npaType;
    }

    /**
     * Sets the value of the npaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeTitleType }
     *     
     */
    public void setNpaType(CodeTitleType value) {
        this.npaType = value;
    }

    /**
     * Gets the value of the npaTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpaTitle() {
        return npaTitle;
    }

    /**
     * Sets the value of the npaTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpaTitle(String value) {
        this.npaTitle = value;
    }

    /**
     * Gets the value of the npaApprovingAuthority property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the npaApprovingAuthority property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNpaApprovingAuthority().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getNpaApprovingAuthority() {
        if (npaApprovingAuthority == null) {
            npaApprovingAuthority = new ArrayList<CodeTitleType>();
        }
        return this.npaApprovingAuthority;
    }

    /**
     * Gets the value of the npaAcceptanceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getNpaAcceptanceDate() {
        return npaAcceptanceDate;
    }

    /**
     * Sets the value of the npaAcceptanceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNpaAcceptanceDate(Date value) {
        this.npaAcceptanceDate = value;
    }

    /**
     * Gets the value of the npaPublicId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpaPublicId() {
        return npaPublicId;
    }

    /**
     * Sets the value of the npaPublicId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpaPublicId(String value) {
        this.npaPublicId = value;
    }

    /**
     * Gets the value of the minustRegistryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getMinustRegistryDate() {
        return minustRegistryDate;
    }

    /**
     * Sets the value of the minustRegistryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMinustRegistryDate(Date value) {
        this.minustRegistryDate = value;
    }

    /**
     * Gets the value of the minustRegistryNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinustRegistryNumber() {
        return minustRegistryNumber;
    }

    /**
     * Sets the value of the minustRegistryNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinustRegistryNumber(String value) {
        this.minustRegistryNumber = value;
    }

    /**
     * Gets the value of the npaLinkPravoGovRu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpaLinkPravoGovRu() {
        return npaLinkPravoGovRu;
    }

    /**
     * Sets the value of the npaLinkPravoGovRu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpaLinkPravoGovRu(String value) {
        this.npaLinkPravoGovRu = value;
    }

    /**
     * Gets the value of the oivData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oivData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOivData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OivDataType }
     * 
     * 
     */
    public List<OivDataType> getOivData() {
        if (oivData == null) {
            oivData = new ArrayList<OivDataType>();
        }
        return this.oivData;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        NPAListItemType that = (NPAListItemType) o;
        return Objects.equals(npaId, that.npaId) && Objects.equals(region, that.region) && Objects.equals(npaType, that.npaType) && Objects.equals(npaTitle, that.npaTitle) && Objects.equals(npaApprovingAuthority, that.npaApprovingAuthority) && Objects.equals(npaAcceptanceDate, that.npaAcceptanceDate) && Objects.equals(npaPublicId, that.npaPublicId) && Objects.equals(minustRegistryDate, that.minustRegistryDate) && Objects.equals(minustRegistryNumber, that.minustRegistryNumber) && Objects.equals(npaLinkPravoGovRu, that.npaLinkPravoGovRu) && Objects.equals(oivData, that.oivData);
    }

    @Override
    public int hashCode() {
        return Objects.hash(npaId, region, npaType, npaTitle, npaApprovingAuthority, npaAcceptanceDate, npaPublicId, minustRegistryDate, minustRegistryNumber, npaLinkPravoGovRu, oivData);
    }
}
