//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.22 at 06:54:51 PM MSK 
//


package rot.tot.ru.rotrequestresponse._1_0;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;


/**
 * <p>Java class for PenaltyAdministrativeResponsibilitySubjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PenaltyAdministrativeResponsibilitySubjectType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="code" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" minOccurs="0"/&gt;
 *         &lt;element name="sanctions" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}SanctionsType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PenaltyAdministrativeResponsibilitySubjectType", propOrder = {
        "id",
    "code",
    "sanctions"
})
@Document
public class PenaltyAdministrativeResponsibilitySubjectType {

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Id
    protected String id;

    protected CodeTitleType code;
    protected List<SanctionsType> sanctions;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CodeTitleType }
     *     
     */
    public CodeTitleType getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeTitleType }
     *     
     */
    public void setCode(CodeTitleType value) {
        this.code = value;
    }

    /**
     * Gets the value of the sanctions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sanctions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSanctions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SanctionsType }
     * 
     * 
     */
    public List<SanctionsType> getSanctions() {
        if (sanctions == null) {
            sanctions = new ArrayList<SanctionsType>();
        }
        return this.sanctions;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PenaltyAdministrativeResponsibilitySubjectType that = (PenaltyAdministrativeResponsibilitySubjectType) o;
        return Objects.equals(code, that.code) && Objects.equals(sanctions, that.sanctions);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, sanctions);
    }
}
