//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.22 at 06:54:51 PM MSK 
//


package rot.tot.ru.rotrequestresponse._1_0;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;


/**
 * <p>Java class for ReferenceDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferenceDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="status" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" minOccurs="0"/&gt;
 *         &lt;element name="categoriesOfPersons" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="categoriesOfPersonsOtherTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mrEstablishmentObject" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="publicRelationSpheres" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="activitySubtype" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="assessmentForm" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="documentReleaseOIV" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="oivRegulator" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="documentReleaseOIVOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="controlTypes" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="interestedOIV" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferenceDataType", propOrder = {
        "id",
    "status",
    "categoriesOfPersons",
    "categoriesOfPersonsOtherTitle",
    "mrEstablishmentObject",
    "publicRelationSpheres",
    "activitySubtype",
    "assessmentForm",
    "documentReleaseOIV",
    "oivRegulator",
    "documentReleaseOIVOther",
    "controlTypes",
    "interestedOIV"
})
@Document
public class ReferenceDataType {

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Id
    protected String id;

    protected CodeTitleType status;
    protected List<CodeTitleType> categoriesOfPersons;
    protected String categoriesOfPersonsOtherTitle;
    protected List<CodeTitleType> mrEstablishmentObject;
    protected List<CodeTitleType> publicRelationSpheres;
    protected List<CodeTitleType> activitySubtype;
    protected List<CodeTitleType> assessmentForm;
    protected List<CodeTitleType> documentReleaseOIV;
    protected List<CodeTitleType> oivRegulator;
    protected String documentReleaseOIVOther;
    protected List<CodeTitleType> controlTypes;
    protected List<CodeTitleType> interestedOIV;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link CodeTitleType }
     *     
     */
    public CodeTitleType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeTitleType }
     *     
     */
    public void setStatus(CodeTitleType value) {
        this.status = value;
    }

    /**
     * Gets the value of the categoriesOfPersons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoriesOfPersons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoriesOfPersons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getCategoriesOfPersons() {
        if (categoriesOfPersons == null) {
            categoriesOfPersons = new ArrayList<CodeTitleType>();
        }
        return this.categoriesOfPersons;
    }

    /**
     * Gets the value of the categoriesOfPersonsOtherTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoriesOfPersonsOtherTitle() {
        return categoriesOfPersonsOtherTitle;
    }

    /**
     * Sets the value of the categoriesOfPersonsOtherTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoriesOfPersonsOtherTitle(String value) {
        this.categoriesOfPersonsOtherTitle = value;
    }

    /**
     * Gets the value of the mrEstablishmentObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mrEstablishmentObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMrEstablishmentObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getMrEstablishmentObject() {
        if (mrEstablishmentObject == null) {
            mrEstablishmentObject = new ArrayList<CodeTitleType>();
        }
        return this.mrEstablishmentObject;
    }

    /**
     * Gets the value of the publicRelationSpheres property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publicRelationSpheres property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublicRelationSpheres().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getPublicRelationSpheres() {
        if (publicRelationSpheres == null) {
            publicRelationSpheres = new ArrayList<CodeTitleType>();
        }
        return this.publicRelationSpheres;
    }

    /**
     * Gets the value of the activitySubtype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activitySubtype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivitySubtype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getActivitySubtype() {
        if (activitySubtype == null) {
            activitySubtype = new ArrayList<CodeTitleType>();
        }
        return this.activitySubtype;
    }

    /**
     * Gets the value of the assessmentForm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assessmentForm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssessmentForm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getAssessmentForm() {
        if (assessmentForm == null) {
            assessmentForm = new ArrayList<CodeTitleType>();
        }
        return this.assessmentForm;
    }

    /**
     * Gets the value of the documentReleaseOIV property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentReleaseOIV property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentReleaseOIV().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getDocumentReleaseOIV() {
        if (documentReleaseOIV == null) {
            documentReleaseOIV = new ArrayList<CodeTitleType>();
        }
        return this.documentReleaseOIV;
    }

    /**
     * Gets the value of the oivRegulator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oivRegulator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOivRegulator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getOivRegulator() {
        if (oivRegulator == null) {
            oivRegulator = new ArrayList<CodeTitleType>();
        }
        return this.oivRegulator;
    }

    /**
     * Gets the value of the documentReleaseOIVOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentReleaseOIVOther() {
        return documentReleaseOIVOther;
    }

    /**
     * Sets the value of the documentReleaseOIVOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentReleaseOIVOther(String value) {
        this.documentReleaseOIVOther = value;
    }

    /**
     * Gets the value of the controlTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controlTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControlTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getControlTypes() {
        if (controlTypes == null) {
            controlTypes = new ArrayList<CodeTitleType>();
        }
        return this.controlTypes;
    }

    /**
     * Gets the value of the interestedOIV property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interestedOIV property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterestedOIV().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getInterestedOIV() {
        if (interestedOIV == null) {
            interestedOIV = new ArrayList<CodeTitleType>();
        }
        return this.interestedOIV;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ReferenceDataType that = (ReferenceDataType) o;
        return Objects.equals(status, that.status) && Objects.equals(categoriesOfPersons, that.categoriesOfPersons) && Objects.equals(categoriesOfPersonsOtherTitle, that.categoriesOfPersonsOtherTitle) && Objects.equals(mrEstablishmentObject, that.mrEstablishmentObject) && Objects.equals(publicRelationSpheres, that.publicRelationSpheres) && Objects.equals(activitySubtype, that.activitySubtype) && Objects.equals(assessmentForm, that.assessmentForm) && Objects.equals(documentReleaseOIV, that.documentReleaseOIV) && Objects.equals(oivRegulator, that.oivRegulator) && Objects.equals(documentReleaseOIVOther, that.documentReleaseOIVOther) && Objects.equals(controlTypes, that.controlTypes) && Objects.equals(interestedOIV, that.interestedOIV);
    }

    @Override
    public int hashCode() {
        return Objects.hash(status, categoriesOfPersons, categoriesOfPersonsOtherTitle, mrEstablishmentObject, publicRelationSpheres, activitySubtype, assessmentForm, documentReleaseOIV, oivRegulator, documentReleaseOIVOther, controlTypes, interestedOIV);
    }
}
