//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.16 at 05:41:47 PM MSK 
//


package com.example.bars;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LinksType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LinksType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="checkListLinks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="guidelineLinks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="reportSuccessLinks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LinksType", propOrder = {
    "checkListLinks",
    "guidelineLinks",
    "reportSuccessLinks"
})
public class LinksType {

    protected String checkListLinks;
    protected String guidelineLinks;
    protected String reportSuccessLinks;

    /**
     * Gets the value of the checkListLinks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckListLinks() {
        return checkListLinks;
    }

    /**
     * Sets the value of the checkListLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckListLinks(String value) {
        this.checkListLinks = value;
    }

    /**
     * Gets the value of the guidelineLinks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuidelineLinks() {
        return guidelineLinks;
    }

    /**
     * Sets the value of the guidelineLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuidelineLinks(String value) {
        this.guidelineLinks = value;
    }

    /**
     * Gets the value of the reportSuccessLinks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportSuccessLinks() {
        return reportSuccessLinks;
    }

    /**
     * Sets the value of the reportSuccessLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportSuccessLinks(String value) {
        this.reportSuccessLinks = value;
    }

}
