//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.16 at 05:41:47 PM MSK 
//


package com.example.bars;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MandatoryRequirementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MandatoryRequirementType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="publicId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="region" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" minOccurs="0"/&gt;
 *         &lt;element name="validityEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="infiniteValidity" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="checkQuestion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="approvingFiles" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="links" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}LinksType" minOccurs="0"/&gt;
 *         &lt;element name="se" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}SeType" minOccurs="0"/&gt;
 *         &lt;element name="referenceData" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}ReferenceDataType" minOccurs="0"/&gt;
 *         &lt;element name="npaKndData" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}NpaKndDataType" minOccurs="0"/&gt;
 *         &lt;element name="penaltyData" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}PenaltyDataType" minOccurs="0"/&gt;
 *         &lt;element name="isDeleted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MandatoryRequirementType", propOrder = {
    "id",
    "publicId",
    "title",
    "region",
    "validityEndDate",
    "infiniteValidity",
    "checkQuestion",
    "approvingFiles",
    "links",
    "se",
    "referenceData",
    "npaKndData",
    "penaltyData",
    "isDeleted"
})
public class MandatoryRequirementType {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String publicId;
    @XmlElement(required = true)
    protected String title;
    protected CodeTitleType region;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validityEndDate;
    protected Boolean infiniteValidity;
    protected String checkQuestion;
    protected String approvingFiles;
    protected LinksType links;
    protected SeType se;
    protected ReferenceDataType referenceData;
    protected NpaKndDataType npaKndData;
    protected PenaltyDataType penaltyData;
    protected Boolean isDeleted;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the publicId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicId() {
        return publicId;
    }

    /**
     * Sets the value of the publicId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicId(String value) {
        this.publicId = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link CodeTitleType }
     *     
     */
    public CodeTitleType getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeTitleType }
     *     
     */
    public void setRegion(CodeTitleType value) {
        this.region = value;
    }

    /**
     * Gets the value of the validityEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidityEndDate() {
        return validityEndDate;
    }

    /**
     * Sets the value of the validityEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidityEndDate(XMLGregorianCalendar value) {
        this.validityEndDate = value;
    }

    /**
     * Gets the value of the infiniteValidity property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInfiniteValidity() {
        return infiniteValidity;
    }

    /**
     * Sets the value of the infiniteValidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInfiniteValidity(Boolean value) {
        this.infiniteValidity = value;
    }

    /**
     * Gets the value of the checkQuestion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckQuestion() {
        return checkQuestion;
    }

    /**
     * Sets the value of the checkQuestion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckQuestion(String value) {
        this.checkQuestion = value;
    }

    /**
     * Gets the value of the approvingFiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovingFiles() {
        return approvingFiles;
    }

    /**
     * Sets the value of the approvingFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovingFiles(String value) {
        this.approvingFiles = value;
    }

    /**
     * Gets the value of the links property.
     * 
     * @return
     *     possible object is
     *     {@link LinksType }
     *     
     */
    public LinksType getLinks() {
        return links;
    }

    /**
     * Sets the value of the links property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinksType }
     *     
     */
    public void setLinks(LinksType value) {
        this.links = value;
    }

    /**
     * Gets the value of the se property.
     * 
     * @return
     *     possible object is
     *     {@link SeType }
     *     
     */
    public SeType getSe() {
        return se;
    }

    /**
     * Sets the value of the se property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeType }
     *     
     */
    public void setSe(SeType value) {
        this.se = value;
    }

    /**
     * Gets the value of the referenceData property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceDataType }
     *     
     */
    public ReferenceDataType getReferenceData() {
        return referenceData;
    }

    /**
     * Sets the value of the referenceData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceDataType }
     *     
     */
    public void setReferenceData(ReferenceDataType value) {
        this.referenceData = value;
    }

    /**
     * Gets the value of the npaKndData property.
     * 
     * @return
     *     possible object is
     *     {@link NpaKndDataType }
     *     
     */
    public NpaKndDataType getNpaKndData() {
        return npaKndData;
    }

    /**
     * Sets the value of the npaKndData property.
     * 
     * @param value
     *     allowed object is
     *     {@link NpaKndDataType }
     *     
     */
    public void setNpaKndData(NpaKndDataType value) {
        this.npaKndData = value;
    }

    /**
     * Gets the value of the penaltyData property.
     * 
     * @return
     *     possible object is
     *     {@link PenaltyDataType }
     *     
     */
    public PenaltyDataType getPenaltyData() {
        return penaltyData;
    }

    /**
     * Sets the value of the penaltyData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PenaltyDataType }
     *     
     */
    public void setPenaltyData(PenaltyDataType value) {
        this.penaltyData = value;
    }

    /**
     * Gets the value of the isDeleted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDeleted() {
        return isDeleted;
    }

    /**
     * Sets the value of the isDeleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDeleted(Boolean value) {
        this.isDeleted = value;
    }

}
