//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.16 at 05:41:47 PM MSK 
//


package com.example.bars;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for NpaKndDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NpaKndDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="npaId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="npaPublicId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="npaTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="npaType" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" minOccurs="0"/&gt;
 *         &lt;element name="npaApprovingAuthority" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="npaAcceptanceDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="npaNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="npaLinkPravoGovRu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NpaKndDataType", propOrder = {
    "npaId",
    "npaPublicId",
    "npaTitle",
    "npaType",
    "npaApprovingAuthority",
    "npaAcceptanceDate",
    "npaNumber",
    "npaLinkPravoGovRu"
})
public class NpaKndDataType {

    protected String npaId;
    protected String npaPublicId;
    protected String npaTitle;
    protected CodeTitleType npaType;
    protected List<CodeTitleType> npaApprovingAuthority;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar npaAcceptanceDate;
    protected String npaNumber;
    protected String npaLinkPravoGovRu;

    /**
     * Gets the value of the npaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpaId() {
        return npaId;
    }

    /**
     * Sets the value of the npaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpaId(String value) {
        this.npaId = value;
    }

    /**
     * Gets the value of the npaPublicId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpaPublicId() {
        return npaPublicId;
    }

    /**
     * Sets the value of the npaPublicId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpaPublicId(String value) {
        this.npaPublicId = value;
    }

    /**
     * Gets the value of the npaTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpaTitle() {
        return npaTitle;
    }

    /**
     * Sets the value of the npaTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpaTitle(String value) {
        this.npaTitle = value;
    }

    /**
     * Gets the value of the npaType property.
     * 
     * @return
     *     possible object is
     *     {@link CodeTitleType }
     *     
     */
    public CodeTitleType getNpaType() {
        return npaType;
    }

    /**
     * Sets the value of the npaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeTitleType }
     *     
     */
    public void setNpaType(CodeTitleType value) {
        this.npaType = value;
    }

    /**
     * Gets the value of the npaApprovingAuthority property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the npaApprovingAuthority property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNpaApprovingAuthority().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getNpaApprovingAuthority() {
        if (npaApprovingAuthority == null) {
            npaApprovingAuthority = new ArrayList<CodeTitleType>();
        }
        return this.npaApprovingAuthority;
    }

    /**
     * Gets the value of the npaAcceptanceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNpaAcceptanceDate() {
        return npaAcceptanceDate;
    }

    /**
     * Sets the value of the npaAcceptanceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNpaAcceptanceDate(XMLGregorianCalendar value) {
        this.npaAcceptanceDate = value;
    }

    /**
     * Gets the value of the npaNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpaNumber() {
        return npaNumber;
    }

    /**
     * Sets the value of the npaNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpaNumber(String value) {
        this.npaNumber = value;
    }

    /**
     * Gets the value of the npaLinkPravoGovRu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpaLinkPravoGovRu() {
        return npaLinkPravoGovRu;
    }

    /**
     * Sets the value of the npaLinkPravoGovRu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpaLinkPravoGovRu(String value) {
        this.npaLinkPravoGovRu = value;
    }

}
