//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.16 at 05:41:47 PM MSK 
//


package com.example.bars;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.bars package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ROTRequest_QNAME = new QName("urn://ru.tot.rot/ROTRequestResponse/1.0.1", "ROTRequest");
    private final static QName _ROTResponse_QNAME = new QName("urn://ru.tot.rot/ROTRequestResponse/1.0.1", "ROTResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.bars
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ROTRequestType }
     * 
     */
    public ROTRequestType createROTRequestType() {
        return new ROTRequestType();
    }

    /**
     * Create an instance of {@link ROTResponseType }
     * 
     */
    public ROTResponseType createROTResponseType() {
        return new ROTResponseType();
    }

    /**
     * Create an instance of {@link NPARequestType }
     * 
     */
    public NPARequestType createNPARequestType() {
        return new NPARequestType();
    }

    /**
     * Create an instance of {@link SURequestType }
     * 
     */
    public SURequestType createSURequestType() {
        return new SURequestType();
    }

    /**
     * Create an instance of {@link MRRequestType }
     * 
     */
    public MRRequestType createMRRequestType() {
        return new MRRequestType();
    }

    /**
     * Create an instance of {@link NPAListType }
     * 
     */
    public NPAListType createNPAListType() {
        return new NPAListType();
    }

    /**
     * Create an instance of {@link NPAListItemType }
     * 
     */
    public NPAListItemType createNPAListItemType() {
        return new NPAListItemType();
    }

    /**
     * Create an instance of {@link OivDataType }
     * 
     */
    public OivDataType createOivDataType() {
        return new OivDataType();
    }

    /**
     * Create an instance of {@link CodeTitleType }
     * 
     */
    public CodeTitleType createCodeTitleType() {
        return new CodeTitleType();
    }

    /**
     * Create an instance of {@link SUListType }
     * 
     */
    public SUListType createSUListType() {
        return new SUListType();
    }

    /**
     * Create an instance of {@link SeType }
     * 
     */
    public SeType createSeType() {
        return new SeType();
    }

    /**
     * Create an instance of {@link RequisitesType }
     * 
     */
    public RequisitesType createRequisitesType() {
        return new RequisitesType();
    }

    /**
     * Create an instance of {@link MRListType }
     * 
     */
    public MRListType createMRListType() {
        return new MRListType();
    }

    /**
     * Create an instance of {@link MandatoryRequirementType }
     * 
     */
    public MandatoryRequirementType createMandatoryRequirementType() {
        return new MandatoryRequirementType();
    }

    /**
     * Create an instance of {@link LinksType }
     * 
     */
    public LinksType createLinksType() {
        return new LinksType();
    }

    /**
     * Create an instance of {@link ReferenceDataType }
     * 
     */
    public ReferenceDataType createReferenceDataType() {
        return new ReferenceDataType();
    }

    /**
     * Create an instance of {@link NpaKndDataType }
     * 
     */
    public NpaKndDataType createNpaKndDataType() {
        return new NpaKndDataType();
    }

    /**
     * Create an instance of {@link PenaltyDataType }
     * 
     */
    public PenaltyDataType createPenaltyDataType() {
        return new PenaltyDataType();
    }

    /**
     * Create an instance of {@link PenaltyAdministrativeResponsibilitySubjectType }
     * 
     */
    public PenaltyAdministrativeResponsibilitySubjectType createPenaltyAdministrativeResponsibilitySubjectType() {
        return new PenaltyAdministrativeResponsibilitySubjectType();
    }

    /**
     * Create an instance of {@link SanctionsType }
     * 
     */
    public SanctionsType createSanctionsType() {
        return new SanctionsType();
    }

    /**
     * Create an instance of {@link MeasureType }
     * 
     */
    public MeasureType createMeasureType() {
        return new MeasureType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ROTRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ROTRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://ru.tot.rot/ROTRequestResponse/1.0.1", name = "ROTRequest")
    public JAXBElement<ROTRequestType> createROTRequest(ROTRequestType value) {
        return new JAXBElement<ROTRequestType>(_ROTRequest_QNAME, ROTRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ROTResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ROTResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "urn://ru.tot.rot/ROTRequestResponse/1.0.1", name = "ROTResponse")
    public JAXBElement<ROTResponseType> createROTResponse(ROTResponseType value) {
        return new JAXBElement<ROTResponseType>(_ROTResponse_QNAME, ROTResponseType.class, null, value);
    }

}
