//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.16 at 05:41:47 PM MSK 
//


package com.example.bars;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for OivDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OivDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="oivCode" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" minOccurs="0"/&gt;
 *         &lt;element name="oivControl" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="controlType" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="categoriesOfPersons" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="activitySubtypes" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="penaltySourceNPAParagraphDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="approveActListActType" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" minOccurs="0"/&gt;
 *         &lt;element name="approveActListDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="approveActListActNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OivDataType", propOrder = {
    "oivCode",
    "oivControl",
    "controlType",
    "categoriesOfPersons",
    "activitySubtypes",
    "penaltySourceNPAParagraphDetails",
    "approveActListActType",
    "approveActListDate",
    "approveActListActNumber"
})
public class OivDataType {

    protected CodeTitleType oivCode;
    protected List<CodeTitleType> oivControl;
    protected List<CodeTitleType> controlType;
    protected List<CodeTitleType> categoriesOfPersons;
    protected List<CodeTitleType> activitySubtypes;
    protected String penaltySourceNPAParagraphDetails;
    protected CodeTitleType approveActListActType;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar approveActListDate;
    protected String approveActListActNumber;

    /**
     * Gets the value of the oivCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeTitleType }
     *     
     */
    public CodeTitleType getOivCode() {
        return oivCode;
    }

    /**
     * Sets the value of the oivCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeTitleType }
     *     
     */
    public void setOivCode(CodeTitleType value) {
        this.oivCode = value;
    }

    /**
     * Gets the value of the oivControl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oivControl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOivControl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getOivControl() {
        if (oivControl == null) {
            oivControl = new ArrayList<CodeTitleType>();
        }
        return this.oivControl;
    }

    /**
     * Gets the value of the controlType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controlType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControlType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getControlType() {
        if (controlType == null) {
            controlType = new ArrayList<CodeTitleType>();
        }
        return this.controlType;
    }

    /**
     * Gets the value of the categoriesOfPersons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoriesOfPersons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoriesOfPersons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getCategoriesOfPersons() {
        if (categoriesOfPersons == null) {
            categoriesOfPersons = new ArrayList<CodeTitleType>();
        }
        return this.categoriesOfPersons;
    }

    /**
     * Gets the value of the activitySubtypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activitySubtypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivitySubtypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getActivitySubtypes() {
        if (activitySubtypes == null) {
            activitySubtypes = new ArrayList<CodeTitleType>();
        }
        return this.activitySubtypes;
    }

    /**
     * Gets the value of the penaltySourceNPAParagraphDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPenaltySourceNPAParagraphDetails() {
        return penaltySourceNPAParagraphDetails;
    }

    /**
     * Sets the value of the penaltySourceNPAParagraphDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPenaltySourceNPAParagraphDetails(String value) {
        this.penaltySourceNPAParagraphDetails = value;
    }

    /**
     * Gets the value of the approveActListActType property.
     * 
     * @return
     *     possible object is
     *     {@link CodeTitleType }
     *     
     */
    public CodeTitleType getApproveActListActType() {
        return approveActListActType;
    }

    /**
     * Sets the value of the approveActListActType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeTitleType }
     *     
     */
    public void setApproveActListActType(CodeTitleType value) {
        this.approveActListActType = value;
    }

    /**
     * Gets the value of the approveActListDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApproveActListDate() {
        return approveActListDate;
    }

    /**
     * Sets the value of the approveActListDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApproveActListDate(XMLGregorianCalendar value) {
        this.approveActListDate = value;
    }

    /**
     * Gets the value of the approveActListActNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApproveActListActNumber() {
        return approveActListActNumber;
    }

    /**
     * Sets the value of the approveActListActNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApproveActListActNumber(String value) {
        this.approveActListActNumber = value;
    }

}
