//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.16 at 05:41:47 PM MSK 
//


package com.example.bars;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for PenaltyDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PenaltyDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="responsibility" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="penaltyNpaTitle" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" minOccurs="0"/&gt;
 *         &lt;element name="penaltyNpaArticle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="penaltyNpaArticleChapter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="penaltyNpaSETitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="penaltyAuthority" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}CodeTitleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="penaltyAdministrativeResponsibilitySubject" type="{urn://ru.tot.rot/ROTRequestResponse/1.0.1}PenaltyAdministrativeResponsibilitySubjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PenaltyDataType", propOrder = {
    "responsibility",
    "penaltyNpaTitle",
    "penaltyNpaArticle",
    "penaltyNpaArticleChapter",
    "penaltyNpaSETitle",
    "penaltyAuthority",
    "penaltyAdministrativeResponsibilitySubject"
})
public class PenaltyDataType {

    protected Boolean responsibility;
    protected CodeTitleType penaltyNpaTitle;
    protected String penaltyNpaArticle;
    protected String penaltyNpaArticleChapter;
    protected String penaltyNpaSETitle;
    protected List<CodeTitleType> penaltyAuthority;
    protected List<PenaltyAdministrativeResponsibilitySubjectType> penaltyAdministrativeResponsibilitySubject;

    /**
     * Gets the value of the responsibility property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isResponsibility() {
        return responsibility;
    }

    /**
     * Sets the value of the responsibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setResponsibility(Boolean value) {
        this.responsibility = value;
    }

    /**
     * Gets the value of the penaltyNpaTitle property.
     * 
     * @return
     *     possible object is
     *     {@link CodeTitleType }
     *     
     */
    public CodeTitleType getPenaltyNpaTitle() {
        return penaltyNpaTitle;
    }

    /**
     * Sets the value of the penaltyNpaTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeTitleType }
     *     
     */
    public void setPenaltyNpaTitle(CodeTitleType value) {
        this.penaltyNpaTitle = value;
    }

    /**
     * Gets the value of the penaltyNpaArticle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPenaltyNpaArticle() {
        return penaltyNpaArticle;
    }

    /**
     * Sets the value of the penaltyNpaArticle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPenaltyNpaArticle(String value) {
        this.penaltyNpaArticle = value;
    }

    /**
     * Gets the value of the penaltyNpaArticleChapter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPenaltyNpaArticleChapter() {
        return penaltyNpaArticleChapter;
    }

    /**
     * Sets the value of the penaltyNpaArticleChapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPenaltyNpaArticleChapter(String value) {
        this.penaltyNpaArticleChapter = value;
    }

    /**
     * Gets the value of the penaltyNpaSETitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPenaltyNpaSETitle() {
        return penaltyNpaSETitle;
    }

    /**
     * Sets the value of the penaltyNpaSETitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPenaltyNpaSETitle(String value) {
        this.penaltyNpaSETitle = value;
    }

    /**
     * Gets the value of the penaltyAuthority property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the penaltyAuthority property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPenaltyAuthority().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeTitleType }
     * 
     * 
     */
    public List<CodeTitleType> getPenaltyAuthority() {
        if (penaltyAuthority == null) {
            penaltyAuthority = new ArrayList<CodeTitleType>();
        }
        return this.penaltyAuthority;
    }

    /**
     * Gets the value of the penaltyAdministrativeResponsibilitySubject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the penaltyAdministrativeResponsibilitySubject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPenaltyAdministrativeResponsibilitySubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PenaltyAdministrativeResponsibilitySubjectType }
     * 
     * 
     */
    public List<PenaltyAdministrativeResponsibilitySubjectType> getPenaltyAdministrativeResponsibilitySubject() {
        if (penaltyAdministrativeResponsibilitySubject == null) {
            penaltyAdministrativeResponsibilitySubject = new ArrayList<PenaltyAdministrativeResponsibilitySubjectType>();
        }
        return this.penaltyAdministrativeResponsibilitySubject;
    }

}
